name: Publish

on:
  push:
    branches: ["main"]
    tags: ["*.*.*"]

jobs:
  main:
    # As of 18/12/2024, Ephemeral Mongo supports only MongoDB 6.0, which is compatible only with Ubuntu 22.04 (https://www.mongodb.com/docs/v6.0/tutorial/install-mongodb-on-ubuntu/)
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v4

      - run: ./Build.ps1
        shell: pwsh
        env:
          NUGET_SOURCE: ${{ secrets.NUGET_SOURCE }}
          NUGET_API_KEY: ${{ secrets.WORKLEAP_NUGET_API_KEY }}

  linearb:
    needs: [main]
    uses: workleap/wl-reusable-workflows/.github/workflows/linearb-deployment.yml@main
    with:
      environment: 'release'
    secrets: inherit
